version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: panel-b2b-marks
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: student
    ports:
      - '5432:5432'
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres: